In [81]:
import numpy as np

In [82]:
A = np.array([[2,5,1],[4,2,0],[1,0,2]])
ans = np.array([3,-1,4])

In [83]:
A_inv = np.linalg.inv(A)

In [84]:
X = np.matmul(A_inv,ans)

In [85]:
x,y,z = X

In [86]:
x

np.float64(-0.41176470588235287)

In [87]:
y

np.float64(0.32352941176470584)

In [88]:
z

np.float64(2.2058823529411766)

In [89]:
2*x + 5*y + z

np.float64(3.0)

In [90]:
4*x + 2*y + 0*z

np.float64(-0.9999999999999998)

In [91]:
x + 0*y + 2*z

np.float64(4.0)

In [92]:
A

array([[2, 5, 1],
       [4, 2, 0],
       [1, 0, 2]])

In [93]:
AT = A.T

In [94]:
AT

array([[2, 4, 1],
       [5, 2, 0],
       [1, 0, 2]])

In [95]:
s = AT.dot(A)

s

array([[21, 18,  4],
       [18, 29,  5],
       [ 4,  5,  5]])

In [101]:
L, V = np.linalg.eig(s)

In [105]:
L

array([44.47764949,  6.56093793,  3.96141259])

In [106]:
V

array([[ 0.61762773,  0.78038207, -0.09767197],
       [ 0.7700018 , -0.62529496, -0.12689933],
       [ 0.16010376, -0.00316895,  0.9870951 ]])

In [107]:
s1, s2, s3 = np.sqrt(L)

In [109]:
s1 , s2, s3

(np.float64(6.669156579846179),
 np.float64(2.561432787657188),
 np.float64(1.9903297686084898))